import './globals.css';
import { Inter } from 'next/font/google';

import Alert from '@/components/Alert';
import Provider from '@/provider';

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-google-sans',
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'MeetProject',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.variable} lang='ko'>
      <body className='relative flex h-svh w-svw'>
        <Alert />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
